<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Tree</name>
   <tag></tag>
   <elementGuidId>8b14de12-1e54-47a2-b820-742a570a15c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(5)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='navbar-top-firstrow']/li[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b9f2f071-0806-41d2-97f5-7887edec34ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tree</value>
      <webElementGuid>97c5d7ba-4e30-4d67-bcda-d3dde1a74ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-top-firstrow&quot;)/li[5]</value>
      <webElementGuid>b838b3ab-fc61-423d-9927-21725049a5f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='navbar-top-firstrow']/li[5]</value>
      <webElementGuid>f8de3b8a-af76-4e3a-bdda-97352f6b14c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]</value>
      <webElementGuid>192c1017-d40e-4a80-bfee-874399a147e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Tree' or . = 'Tree')]</value>
      <webElementGuid>c38dc83b-0bf5-448b-8b35-5abd7e460356</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
