<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BooleanCoercer</name>
   <tag></tag>
   <elementGuidId>953fd5cd-62f7-4906-9ba5-c4a1d837db94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;class in org.openqa.selenium.json&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='class-summary.tabpanel']/div/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c3b28c17-7809-44f0-ac3a-de4b25932e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>BooleanCoercer.html</value>
      <webElementGuid>aef2ffec-16cc-4d6f-88b8-0fc79493b8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium.json</value>
      <webElementGuid>ec262dfe-02ef-462c-b2d8-50616f51a48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BooleanCoercer</value>
      <webElementGuid>5f13829e-349d-4035-be70-654344cb3494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;class-summary.tabpanel&quot;)/div[@class=&quot;summary-table two-column-summary&quot;]/div[@class=&quot;col-first even-row-color class-summary class-summary-tab2&quot;]/a[1]</value>
      <webElementGuid>1b589112-5dc7-4686-b2b1-7040c46427ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='class-summary.tabpanel']/div/div[3]/a</value>
      <webElementGuid>aaa1ec0e-926a-4e3c-9d80-9e897308a7b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BooleanCoercer')]</value>
      <webElementGuid>9d9943a9-fb7a-4302-bfa8-9c24b619f3ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'BooleanCoercer.html')]</value>
      <webElementGuid>9791db1c-7cb1-4193-a7e4-6b5f43ccf474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/a</value>
      <webElementGuid>554bb384-a4d9-4b5d-a32f-121d3669938b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'BooleanCoercer.html' and @title = 'class in org.openqa.selenium.json' and (text() = 'BooleanCoercer' or . = 'BooleanCoercer')]</value>
      <webElementGuid>f7bb1b0a-b218-46dd-bb97-b29270a97399</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
